### ISSUE TITLE
Application failed to start

### ISSUE THREAD

**Issue by felloumi** [taunometsalu/ClustVis#3]
Hi,
Trying to run the docker, I got this error:
The application failed to start.

The application exited during initialization.

-su: line 0: cd: /srv/shiny-server: Permission denied.

Any suggestions to solve the issue?

Thanks

**Comment by taunometsalu** [comment]
Probably I have missed changing user rights in the container. Something like should be run inside the container:

`chown -R shiny:shiny /srv/shiny-server`

**Comment by felloumi** [comment]
I did and committed to had a new image. Using the new image I had no connection at all. Could you guide me on the right way?

Thanks.

**Comment by taunometsalu** [comment]
I cannot reproduce, I tried in a different environment and it works without changing any rights.

Perhaps there is some another issue with user rights, e.g. no read access to the folder ~/customClustvis/ClustVis-master/?

**Comment by joshuabhk** [comment]
At least, in my settings, I fixed a similar issue by allowing "other" users can read and execute (chmod -R go+rx ~/customClustvis/).

At first, I was puzzled that since I ran docker with "sudo", so it should be able to read and run regardless of the permissions, but anyways it fixed our issue.

Hope this helps!

**Comment by taunometsalu** [comment]
Thanks, joshuabhk, I added this to the instructions!
